Question 1

In [ ]:
# 1. Vector (1D Array)

# A vector is simply a one-dimensional NumPy array.

# 2. Matrix (2D Array)

# A matrix is a two-dimensional NumPy array consisting of rows and columns.

Question 2

In [11]:
import numpy as np

Question 3

In [12]:
list_1 = [1,2,3,4,5]
list_1_arr = np.array(list_1)
print(list_1_arr)
print(type(list_1_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Question 4

In [7]:
arr = np.arange(0,6)
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Question 5

In [8]:
arr = np.zeros(5)
print(arr)
print(type(arr))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


Question 6

In [10]:
arr = np.zeros((3,4))
print(arr)
print(type(arr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


Question 7

In [13]:
arr = np.ones(5)
print(arr)
print(type(arr))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Question 8

In [16]:
arr = np.full((1,5),10)
print(arr)
print(type(arr))

[[10 10 10 10 10]]
<class 'numpy.ndarray'>


Question 9 

In [18]:
arr = np.arange(52,100,2)
print(arr)
print(type(arr))

[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
<class 'numpy.ndarray'>


Question 10

In [23]:
arr = np.linspace(0,1,10,retstep=True)
print(arr)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), np.float64(0.1111111111111111))


Question 11

In [29]:
arr = np.arange(0,25)
print(arr)
arr1 = arr.reshape((5,5))
print(arr1)
# We can use shape as well.The difference is that the shape method just changes the shape of the array.It does not return a new array. 
arr.shape = (5,5)
print(arr)  

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


C:\Users\SkyTech\AppData\Local\Temp\ipykernel_8176\643105724.py:6: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  arr.shape = (5,5)


Question 12

In [32]:
arr = np.arange(0.1,2.6,0.1)
arr2 = arr.reshape(5,5)
print(arr2)

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]]


Question 13

In [35]:
arr = np.linspace(0,24,25)
print(arr.reshape(5,5))

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


Question 14

In [ ]:
# The main difference is what one specifies to generate the numbers.

# np.arange()	                      np.linspace()
# Specify the step size.	     Specify the number of values.
# Stop value is excluded.	     Stop value is included by default.
# Best for evenly spaced values  Best for generating a fixed number 
# with a fixed interval.         of equally spaced values.

Question 15

In [37]:
print(np.random.randint(0,100,1))

[97]


Question 16

In [38]:
print(np.random.rand(7,5))

[[0.22420075 0.28797877 0.90715105 0.87493273 0.84211066]
 [0.74004764 0.8627825  0.36479057 0.38635125 0.22998359]
 [0.04761861 0.03133624 0.02760676 0.28604469 0.84920806]
 [0.96222208 0.77242142 0.07564102 0.27569468 0.66829207]
 [0.60041463 0.9893139  0.93340395 0.26759621 0.86988621]
 [0.87265365 0.08244603 0.41996449 0.68907629 0.74700235]
 [0.80445941 0.81715582 0.84667126 0.55333861 0.05930737]]


Question 17

In [39]:
arr = 5 * np.eye(5)
print(arr)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
